testTaskBundle:
    resource: "@testTaskBundle/Controller/"
    type:     annotation
    prefix:   /

testHelloBundle:
    resource: "@testHelloBundle/Resources/config/routing.yml"
    prefix:   /

BloggerBlogBundle:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
